<?php

/**
 * view script failed-login
 * Displays errors to users when social log-in or registration fails
 * 
 * @package     Social
 * @author      Nigel Hurnell
 * @version     v.1.0.0
 * @license     BSD
 * @copyright   Copyright (c) 2017, Nigel Hurnell
 */

namespace Social;

?>
<?= $this->headTitle('Unknown Provider') ?>
<ul class="alert alert-danger">
    <li><?= $this->translate("You have tried to register with a provider that is unknown or is not enabled.") ?></li>
</ul>
