<?php
/**
 * View script change-password
 *
 * @package     AclUser
 * @author      Nigel Hurnell
 * @version     v.1.0.0
 * @license     BSD
 * @since       25 Jan 2018
 * @copyright   Copyright (c) 2018, Nigel Hurnell 
 */

namespace AclUser;
?>
<?php $this->headTitle('Change Password'); ?>
<div class = "row">
    <div class = "col-md-offset-3 col-md-6">
        <!--?= $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?-->
        <?= $this->form()->openTag($form); ?>
        <h2><?= $this->translate('Change Your Password') ?></h2>
        <table class="user-auth">
            <?php if ($withOldPassword): ?>
                <tr>
                    <td class="right"><?= $this->formLabel($form->get('old_password')); ?></td>
                    <td><?= $this->formElement($form->get('old_password')); ?></td>
                </tr>
                <tr>

                    <td><?= $this->formElementErrors($form->get('old_password')); ?></td>
                </tr>
            <?php endif; ?>
            <tr>
                <td class="right"><?= $this->formLabel($form->get('new_password')); ?></td>
                <td><?= $this->formElement($form->get('new_password')); ?></td>
            </tr>
            <tr>

                <td colspan="2"><?= $this->formElementErrors($form->get('new_password')); ?></td>
            </tr>
            <tr>
                <td class="right"><?= $this->formLabel($form->get('confirm_new_password')); ?></td>
                <td><?= $this->formElement($form->get('confirm_new_password')); ?></td>
            </tr>
            <tr>
                <td colspan="2"><?= $this->formElementErrors($form->get('confirm_new_password')); ?></td>
            </tr>
            <tr>
                <td colspan="2"><?= $this->formElement($form->get('submit')) ?></td>
            </tr>
        </table>
        <?= $this->formElement($form->get('csrf')) ?>
        <?= $this->formElementErrors($form->get('csrf')) ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>

