<?php
/**
 * File edit.phtml file that should be rendered so that authorised user
 * can choose specific message in chosen language to update
 * 
 *
 * @package     Translate
 * @author      Nigel Hurnell
 * @version     v 1.0.0
 * @license     BSD
 * @copyright   Copyright (c) 2017, Nigel Hurnell
 */

namespace Translate;

$this->headTitle('Edit Translations');
$this->headScript()->appendFile('/js/tables/table-sorter.js', 'text/javascript');
$this->headScript()->appendFile('/js/translate/edit-languages.js', 'text/javascript');
$others = [
    'untranslated' => ['type' => 'all', 'title' => 'All', 'original'],
    'all' => ['type' => 'untranslated', 'title' => 'Untranslated'],
];
?>

<h1><?= $this->translate('Edit Translations') . ' - ' . $this->translate('English') . ' -> ' . $this->translate($locale); ?></h1>
<?php ?>
<p class='right'>
    <a href="<?= $this->url('translate', ['action' => 'edit', 'language' => $locale, 'type' => $others[$type]['type']]); ?>" class="btn btn-primary">
        <?= $this->translate($others[$type]['title']); ?>
    </a>
</p>

<table class="table">
    <tr class='header'>
        <th class='no_sort'>&nbsp;</th>
        <th class='sortable'><?= $this->translate('Original'); ?></th>
        <th class='sortable'><?= $this->translate('Translation'); ?></th>
    </tr>
    <?php foreach ($translations as $translation) : ?>
        <tr>
            <td>
                <a href="<?= $this->url('translate', ['action' => 'edit-translation', 'language' => $locale, 'type' => $type, 'idx' => $translation['idx'], 'index' => $translation['index']]); ?>" class="btn btn-primary">
                    <?= $this->translate('Translate'); ?>
                </a>
            </td>
            <td title="<?= $translation['filepath']; ?>"><?= $this->escapeHtml($translation['msgid']) ?></td>
            <td><?= $this->escapeHtml($translation['msgstr']) ?></td>
        </tr>
    <?php endforeach; ?>
</table>