<?php
/**
 * view-script partial - puts the html for ajax popup
 *
 * @package     Application
 * @author      Nigel Hurnell
 * @version     v 1.0.0
 * @license     BSD
 * @copyright   Copyright (c) 2017, Nigel Hurnell
 */
namespace Application;
?>

<div id="outer-popup-holder" class="hide-popup-div">
    <div id="popup-holder">
        <div id="popup-inner">&nbsp;

        </div>
    </div>
</div>