<?php
/**
 * view script forgotten password-email
 *
 * @package     AclUser
 * @author      Nigel Hurnell
 * @version     v.1.0.0
 * @license     BSD
 * @copyright   Copyright (c) 2017, Nigel Hurnell
 */

namespace AclUser;
?>
<p><?= $this->translate('Dear') ?> <?= $user->getFullName() ?>,</p>
<p><?= $this->translate('Please follow the link below to reset your password') ?>:</p>
<?php
$href = $this->url('send-token', ['action' => 'reset-password', 'token' => $token, 'locale' => $this->layout()->locale], ['force_canonical' => true])
?>
<p><a href="<?= $href ?>" ><?= $href ?></a></p>
<p><?= $this->translate('Please note that this reset password token will expire in six hours') ?></p>
