<?php
/**
 * View script ajax-get-basic-profile-form
 *
 * @package     Acluser
 * @author      Nigel Hurnell
 * @version     v.0.0.1
 * @license     BSD
 * @uses        Zend Framework 3
 * @since       8 Mar 2018
 * @copyright   Copyright (c) 2018, Nigel Hurnell 
 */

namespace Acluser;

$form->setAttribute('action', $action);
?>
<div id="basic-profile-form-holder">
    <?= $this->form()->openTag($form); ?>
    <h2 class="center-content"><?= $this->translate('Update Profile') ?></h2>
    <table class="user-profile"> 
        <tr>
            <td class="right"><?= $this->formLabel($form->get('full_name')); ?></td>
            <td><?= $this->formElement($form->get('full_name')); ?></td>
        </tr>
        <tr>
            <td colspan="2" class="full-name-errors"><?= $this->formElementErrors($form->get('full_name')); ?></td>
        </tr>
        <tr>
            <td class="right"><?= $this->formLabel($form->get('email')); ?></td>
            <td><?= $this->formElement($form->get('email')); ?></td>
        </tr>
        <tr>
            <td colspan="2" class="email-errors"><?= $this->formElementErrors($form->get('email')); ?></td>
        </tr>
        <tr>
            <td colspan="2"><?= $this->formElement($form->get('submit')) ?></td>
        </tr>
    </table>
    <?= $this->formElement($form->get('csrf')) ?>
    <span class="csrf-errors"><?= $this->formElementErrors($form->get('csrf')) ?></span>
    <?= $this->form()->closeTag(); ?>
</div>

