<?php
/**
 * view script forgotten password
 *
 * @package     AclUser
 * @author      Nigel Hurnell
 * @version     v.1.0.0
 * @license     BSD
 * @copyright   Copyright (c) 2017, Nigel Hurnell
 */

namespace AclUser;

$this->headTitle('Forgotten Password');

$form->get('email')->setAttributes([
    'class' => 'form-control',
    'placeholder' => 'Email address'
]);

$form->get('submit')->setAttributes([
    'class' => 'btn btn-large btn-primary'
]);

$form->prepare();
?>

<div class="row">
    <div class="col-md-offset-4 col-md-4">
        <?= $this->form()->openTag($form); ?>
        <h2><?= $this->translate('Reset Password'); ?></h2>
        <?= $this->flashMessenger()->render('error', array('alert', 'alert-danger')); ?>
        <?= $this->flashMessenger()->setTranslatorEnabled(false)->render('email', array('alert', 'alert-danger')); ?>
        <?= $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
        <?= $this->flashMessenger()->setTranslatorEnabled(false)->render('email-success', array('alert', 'alert-success')); ?>
        <p><?= $this->translate('Enter your e-mail here to reset your password'); ?></p>
        <?= $this->formElement($form->get('email')); ?>
        <?= $this->formElementErrors($form->get('email')); ?>                              

        <?= $this->formElement($form->get('captcha')); ?>
        <p class="hint"><?= $this->translate('Enter the letters above as you see them.'); ?></p>
        <?= $this->formElement($form->get('submit')); ?>
        <?= $this->formElement($form->get('csrf')); ?>
        <?= $this->form()->closeTag(); ?>
    </div>
</div>
