<?php
/**
 * view script profile
 *
 * @package     AclUser
 * @author      Nigel Hurnell
 * @version     v.1.0.0
 * @license     BSD
 * @copyright   Copyright (c) 2017, Nigel Hurnell
 */

namespace AclUser;
?>
<div id="profile-div" class="col-md-offset-4 col-md-4">
    <h2 class="center-content"><?= $this->translate('Your Profile'); ?></h2>
    <?= $this->partial('partials/profile-partial.phtml'); ?>
    <p><a href="<?= $this->url('default', ['controller' => 'user-auth', 'action' => 'change-password']); ?>"><?= $this->translate('Change Password'); ?></a></p>
</div>

